### ISSUE TITLE
Errors when go-getting

### ISSUE THREAD

**Issue by dre1080** [upper/bond#3]
I get the following errors when I go get bond:

```
go get upper.io/bond

# upper.io/bond
../../../upper.io/bond/mapper.go:25: undefined: reflectx.StructMap
../../../upper.io/bond/mapper.go:26: undefined: reflectx.FieldInfo
```

**Comment by pkieltyka** [comment]
@dre1080 hey, just saw this now. Did you figure it out btw..? the reason was previously it required a branch of sqlx/reflectx, but that stuff is now in master for github.com/jmoiron/sqlx
