### ISSUE TITLE
Archive this repo

### ISSUE THREAD

**Issue by VojtechVitek** [upper/bond#32]
Hi @xiam,
can we archive this repo?

We've forked upper/bond internally in Pressly and made some breaking API changes.. I don't intend to merge this back to upstream, nor maintain this repo.

Thanks

**Comment by pkieltyka** [comment]
hey @VojtechVitek why would you suggest to archive it? we don't need you to maintain it..?

we use it at Horizon, so definitely not going to archive it. But we can delete the "pressly" branch if you have a fork

**Comment by VojtechVitek** [comment]
@pkieltyka cool, didn't know you guys use it in Horizon. Thanks for letting me know

**Comment by pkieltyka** [comment]
Yea :) I use it in my places
