### ISSUE TITLE
Support for query transactions

### ISSUE THREAD

**Issue by xiam** [upper/bond#4]
Currently bond does not support transactions. I opened this issue to discuss about what would be the best way to implement transactions in bond.

In `upper.io/db` we have the `db.Database.Transaction()` method which opens a new connection that allows the transaction to happen without blocking the original connection.

We could do something very similar in bond, maybe something like this:

``` go
// DB implements bond.Session

tx, err := DB.Transaction()

// This is a bond.Session Save()
_ = tx.Save(newArtist)

// This is a bond.Store Save()
_ = tx.ArtistAccess.Save(aa)

_ = tx.Commit()
```

In this case, we would have some problems here with `bond.Store` because of its cached `db.Collection` property, which is a collection that always uses the original database connection instead of the transaction. I already tested an experimental change that fixes that by using a function that returns the appropriate `db.Collection` whenever `bond.Store.Save()` or any other `bond.Store` method that needs a collection is called. `upper.io/db` recently added a [similar caching](https://github.com/upper/db/pull/101) mechanism which we could use right away.

The thing with this `DB.Transaction()` is that, in order for it to have a `ArtistAccess` property, it must be exactly of the same type as `DB` (because `ArtistAccess` does not exists in any other context), which will require the user to do some manual wrapping which looks confusing:

``` go
type Database struct {
  bond.Session
  ArtistAccess ArtistAccessStore
}

var DB *Database

// Transaction is a wrapper around BeginTransaction, which is
// the actual way to start a transaction in bond.
func (d *Database) Transaction() (*Database, error) {
   nd := new(Database)
   sess, err := d.Session.BeginTransaction()
   if err != nil {
     return nil, err
   }
   nd.Session = sess
   return nd, nil
}
```

If we didn't want DB to have a `ArtistAccess` property, we would have to use `bond.Session.Save`:

``` go
tx, err := DB.Transaction()

// This is a bond.Session Save()
_ = tx.Save(newArtist)

// This is a bond.Store Save()
_ = tx.Save(artistAccessValue)

_ = tx.Commit()
```

That way the user would not have to do any extra coding by herself, but also makes `tx` a bit different from `DB`, which is also a bit confusing.

What do you think @pkieltyka?

**Comment by xiam** [comment]
It just occurred to me that we can use another trick for this context switching:

```
DB.ArtistAccess.With(tx).Save(aa)
```

The main problem is how to tell `DB.ArtistAccess` to use `tx` instead of the original database session, we could use this `With()` method instead of copying the whole DB struct as I did above.

**Comment by pkieltyka** [comment]
good thinking and I think this would be a very nice feature to have in bond.

what if we had a Tx() method on bond.Store ..? which started the new transaction for that store.. pretty much just a flip of what you're saying. Example:

``` go
tx := DB.ArtistAccess.Tx()

// this is a bond.Tx for a bond.Store, that is in fact very similar to bond.Store (which can save, and whatever else we think it should do)
_ = tx.Save(aa)

_ = tx.Commit()
```

**Comment by pkieltyka** [comment]
or even

``` go
tx, err := DB.ArtistAccess.Tx()
```

.. not sure what the error would return (I haven't looked at details.. ie. it can't create the transaction at db level). The nice thing about the multi-value return is it prevents people from trying to do 1 line magic and forget to .Commit() or .Rollback()

**Comment by xiam** [comment]
> what if we had a Tx() method on bond.Store ..? which started the new transaction for that store.. pretty much just a flip of what you're saying. Example:

That's possible, but what about the case where the user wants to affect two different collections/stores in the same transaction? (artists, and artist_access)
